variables:
  PROJECT_NAMESPACE: my-namespace
  CI_PROJECT_NAME: my-project
  IMAGE_TAG: v1.0.0
  IMAGE_NAME: pyapp
  USER_NAME: siarheisaroka
image: python:3.8-slim-buster
before_script:
- sudo apt-get update -y && apt-get install -y curl make git
stages:
- test
- build
- push

lint:
  tags:
  - gcp
  stage: test
  script:
  - whoami
  - sudo make lint

run_tests:
  tags:
  - gcp
  stage: test
  script:
  - make test
  needs:
  - job: lint

build_image:
  tags:
  - gcp
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  stage: build
  image: docker:20.10.16
  services:
  - docker:20.10.16-dind
  before_script: []
  script:
  - docker -v
  - echo "vars DOCKER_HOST:$DOCKER_HOST, DOCKER_DRIVER:$DOCKER_DRIVER"
  - docker login -u $DOCKER_USER_NAME -p $CI_BUILD_TOKEN
  - sleep 20
  - apk add iproute2
  - apk add git
  - ss -ntpl
  - docker build --network=host -t $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG -f build/Dockerfile .
  - docker image save $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG -o build/$IMAGE_NAME.tar.gz
  artifacts:
    paths:
    - build/

push_image:
  tags:
  - gcp
  variables:
    DOCKER_HOST: tcp://docker:2375
    #DOCKER_DRIVER: overlay2
  stage: push
  image: docker:20.10.16
  services:
  - docker:20.10.16-dind
  before_script: []
  script:
  - echo "stage push"
  - sleep 20
  - docker load -i build/$IMAGE_NAME.tar.gz
  - docker login -u $DOCKER_USER_NAME -p $CI_BUILD_TOKEN
  - docker push $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG
  dependencies:
  - build_image



