variables:
  PROJECT_NAMESPACE: my-namespace
  CI_PROJECT_NAME: my-project
  IMAGE_TAG: v1.0.0
  IMAGE_NAME: pyapp
  USER_NAME: siarheisaroka
image: python:3.8-slim-buster
before_script:
- apt-get update -y && apt-get install -y curl make git
stages:
- test
- build
- push

lint:
  stage: test
  script:
  - make lint

run_tests:
  stage: test
  script:
  - make test
  needs:
  - job: lint

build_image:
  image: docker:20
  services:
  - docker:dind
  stage: build
  script:
  - echo "stage build"

push_image:
  stage: push
  script:
  - echo "stage deploy"
